services:
  backend:
    build: backend
    restart: always
    volumes: 
      - ./data:/app/backend/data
    ports:
      - 3000:3000

  frontend:
    build: 
      context: frontend
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
